### ISSUE TITLE
Path of Het puzzle room tick counter

### ISSUE THREAD

**Issue by YvesW** [LlemonDuck/tombs-of-amascut#25] opened 2022-09-28 08:00 UTC
It'd be lovely if a tick counter could be added that is visible when you are in the puzzle room of the path of Het. The counter could either start and reset when the statue fires its laser, or if that is deemed too powerful, the counter could start when the player enters the room. This way players don't need to have a tick counter (e.g. on the report button) enabled all the time for the 1 shot trick.

**Comment by LlemonDuck** [comment] 2022-09-28 08:08
Duplicate of #19

**Closed by LlemonDuck** 2022-09-28 08:08 UTC
