### ISSUE TITLE
enable entity hider during P4 warden

### ISSUE THREAD

**Issue by JustusLuijckx** [LlemonDuck/tombs-of-amascut#58] opened 2023-04-02 13:04 UTC
It's a huge advantage to be able to see the tiles under you properly during P4, its also something you can enable manually but I think the plugin doing it for you would be super nice. Don't think it's against the rules.

**Comment by LlemonDuck** [comment] 2023-04-09 04:11
Duplicate of #55

**Closed by LlemonDuck** 2023-04-09 04:11 UTC
